name: relative_scale
description: RelativeScale is a simple custom sizing system for flutter widgets to achieve the same physical sizes across different devices.
version: 2.0.0
homepage: https://github.com/xamantra/flutter_relative_scale

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter